// List of all required DOM element IDs
var DOM_IDS = [
  'video', 'overlay', 'loading', 'pageTitle', 'gestureControls',
  'trackingOffsetControls',
  'trackingOffsetXSlider', 'trackingOffsetXValue',
  'trackingOffsetYSlider', 'trackingOffsetYValue',
  'toolTagControls',
  'isovistTagSelect', 'shortestPathTagSelect', 'panTagSelect', 'zoomTagSelect', 'eraserTagSelect', 'nextTagSelect', 'backTagSelect',
  'geojsonImportBtn', 'geojsonFileInput', 'geojsonFilesList',
  'holdStillThresholdSlider', 'holdStillThresholdValue',
  'dwellTimeSlider', 'dwellTimeValue',
  'pinchHoldTimeSlider', 'pinchHoldTimeValue',
  'apriltagMoveWindowSlider', 'apriltagMoveWindowValue',
  'apriltagMoveDistanceSlider', 'apriltagMoveDistanceValue',
  'strokeStopDelaySlider', 'strokeStopDelayValue',
  'pointerLostTimeoutSlider', 'pointerLostTimeoutValue',
  'drawingDeselectTimeoutSlider', 'drawingDeselectTimeoutValue',
  'surfaceButtons', 'surfaceBtn1', 'surfaceBtn2', 'surfaceBtn3', 'surfaceBtn4', 'apriltagCalibBtn',
  'backBtn', 'startBtn', 'showResultsBtn', 'nextBtn', 'stopBtn',
  'viewToggleContainer', 'viewToggle',
  'apriltagHud',
  'mapView', 'mapWarp', 'leafletMap', 'mapFingerDots',
  'mapApriltagDots', 'mapTagMasks',
  'resultsViewerControls', 'resultsViewTitle', 'resultsViewMeta', 'resultsPrevBtn', 'resultsNextBtn', 'resultsExitBtn',
  'mapSessionPanel', 'mapSessionAddBtn', 'mapSessionList',
  'hamburgerMenu', 'hamburgerBtn', 'hamburgerPanel', 'hamburgerContent',
  'resultsModal', 'resultsModalBackdrop', 'resultsWorkshopSelect', 'resultsOpenBtn', 'resultsCancelBtn', 'resultsError',
  'uiSetupOverlay', 'uiSetupPanel', 'mapFingerCursor', 'edgeGuides', 'error'
];

// Mapping from camelCase property names to element IDs
var ID_TO_PROP = {
  'video': 'video',
  'overlay': 'overlay',
  'loading': 'loadingEl',
  'pageTitle': 'pageTitleEl',
  'gestureControls': 'gestureControlsEl',
  'trackingOffsetControls': 'trackingOffsetControlsEl',
  'trackingOffsetXSlider': 'trackingOffsetXSliderEl',
  'trackingOffsetXValue': 'trackingOffsetXValueEl',
  'trackingOffsetYSlider': 'trackingOffsetYSliderEl',
  'trackingOffsetYValue': 'trackingOffsetYValueEl',
  'toolTagControls': 'toolTagControlsEl',
  'isovistTagSelect': 'isovistTagSelectEl',
  'shortestPathTagSelect': 'shortestPathTagSelectEl',
  'panTagSelect': 'panTagSelectEl',
  'zoomTagSelect': 'zoomTagSelectEl',
  'eraserTagSelect': 'eraserTagSelectEl',
  'nextTagSelect': 'nextTagSelectEl',
  'backTagSelect': 'backTagSelectEl',
  'geojsonImportBtn': 'geojsonImportBtnEl',
  'geojsonFileInput': 'geojsonFileInputEl',
  'geojsonFilesList': 'geojsonFilesListEl',
  'holdStillThresholdSlider': 'holdStillThresholdSliderEl',
  'holdStillThresholdValue': 'holdStillThresholdValueEl',
  'dwellTimeSlider': 'dwellTimeSliderEl',
  'dwellTimeValue': 'dwellTimeValueEl',
  'pinchHoldTimeSlider': 'pinchHoldTimeSliderEl',
  'pinchHoldTimeValue': 'pinchHoldTimeValueEl',
  'apriltagMoveWindowSlider': 'apriltagMoveWindowSliderEl',
  'apriltagMoveWindowValue': 'apriltagMoveWindowValueEl',
  'apriltagMoveDistanceSlider': 'apriltagMoveDistanceSliderEl',
  'apriltagMoveDistanceValue': 'apriltagMoveDistanceValueEl',
  'strokeStopDelaySlider': 'strokeStopDelaySliderEl',
  'strokeStopDelayValue': 'strokeStopDelayValueEl',
  'pointerLostTimeoutSlider': 'pointerLostTimeoutSliderEl',
  'pointerLostTimeoutValue': 'pointerLostTimeoutValueEl',
  'drawingDeselectTimeoutSlider': 'drawingDeselectTimeoutSliderEl',
  'drawingDeselectTimeoutValue': 'drawingDeselectTimeoutValueEl',
  'surfaceButtons': 'surfaceButtonsEl',
  'surfaceBtn1': 'surfaceBtn1',
  'surfaceBtn2': 'surfaceBtn2',
  'surfaceBtn3': 'surfaceBtn3',
  'surfaceBtn4': 'surfaceBtn4',
  'apriltagCalibBtn': 'apriltagCalibBtn',
  'backBtn': 'backBtn',
  'startBtn': 'startBtn',
  'showResultsBtn': 'showResultsBtn',
  'nextBtn': 'nextBtn',
  'stopBtn': 'stopBtn',
  'viewToggleContainer': 'viewToggleContainerEl',
  'viewToggle': 'viewToggleEl',
  'apriltagHud': 'apriltagHudEl',
  'mapView': 'mapViewEl',
  'mapWarp': 'mapWarpEl',
  'leafletMap': 'leafletMapEl',
  'mapFingerDots': 'mapFingerDotsEl',
  'mapApriltagDots': 'mapApriltagDotsEl',
  'mapTagMasks': 'mapTagMasksEl',
  'resultsViewerControls': 'resultsViewerControlsEl',
  'resultsViewTitle': 'resultsViewTitleEl',
  'resultsViewMeta': 'resultsViewMetaEl',
  'resultsPrevBtn': 'resultsPrevBtnEl',
  'resultsNextBtn': 'resultsNextBtnEl',
  'resultsExitBtn': 'resultsExitBtnEl',
  'mapSessionPanel': 'mapSessionPanelEl',
  'mapSessionAddBtn': 'mapSessionAddBtnEl',
  'mapSessionList': 'mapSessionListEl',
  'hamburgerMenu': 'hamburgerMenuEl',
  'hamburgerBtn': 'hamburgerBtnEl',
  'hamburgerPanel': 'hamburgerPanelEl',
  'hamburgerContent': 'hamburgerContentEl',
  'resultsModal': 'resultsModalEl',
  'resultsModalBackdrop': 'resultsModalBackdropEl',
  'resultsWorkshopSelect': 'resultsWorkshopSelectEl',
  'resultsOpenBtn': 'resultsOpenBtnEl',
  'resultsCancelBtn': 'resultsCancelBtnEl',
  'resultsError': 'resultsErrorEl',
  'uiSetupOverlay': 'uiSetupOverlayEl',
  'uiSetupPanel': 'uiSetupPanelEl',
  'mapFingerCursor': 'mapFingerCursorEl',
  'edgeGuides': 'edgeGuidesEl',
  'error': 'errorEl'
};

export function getDom() {
  var dom = {};
  for (var i = 0; i < DOM_IDS.length; i++) {
    var id = DOM_IDS[i];
    var el = document.getElementById(id);
    if (!el) {
      throw new Error('Missing DOM element: ' + id);
    }
    var propName = ID_TO_PROP[id] || id;
    dom[propName] = el;
  }
  return dom;
}
